application: studentplanneronline
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  script: main.app
- url: /welcome
  script: main.app
  
- url: /timetable
  script: timetable.app
  login: required
- url: /createtimetable
  script: timetable.app
  login: required
- url: /edittimetable
  script: timetable.app
  login: required
  
- url: /event
  script: event.app
  login: required
- url: /createevent
  script: event.app
  login: required
- url: /editevent
  script: event.app
  login: required
- url: /deleteevent
  script: event.app
  login: required
  
- url: /dev/agent
  script: dev.app
  
- url: /admin/weekswitch
  script: cronjobs.app
  login: admin
  
- url: /favicon\.ico
  static_files: logo37x37.ico
  upload: favicon\.ico
- url: /resource
  static_dir: resource
  
- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
